baseURL: http://localhost/
title: Hugo Bootstrap Framework (HB)
copyright: "Copyright © 2022-{year} [Razon Yang](https://github.com/razonyang). All Rights Reserved."
defaultContentLanguageInSubdir: true
disqusShortname: hb-site

module:
  # proxy: https://goproxy.cn
  imports:
    # site modules
    - path: github.com/razonyang/hugo-mod-seo
    - path: github.com/razonyang/hugo-mod-html
    - path: github.com/razonyang/hb/modules/progress-bar
    - path: github.com/razonyang/hb/modules/back-to-top
    - path: github.com/razonyang/hb/modules/base
    - path: github.com/razonyang/hb/modules/pwa
    - path: github.com/razonyang/hb/modules/code-block-panel
    - path: github.com/razonyang/hb/modules/mermaid
    - path: github.com/razonyang/hb/modules/bootstrap
    # icons modules
    - path: github.com/razonyang/hugo-mod-icons/vendors/simple-icons
    - path: github.com/razonyang/hugo-mod-icons/vendors/font-awesome
    # header modules
    - path: github.com/razonyang/hb/modules/header/modules/search
    - path: github.com/razonyang/hb/modules/header/modules/theme-toggle
    - path: github.com/razonyang/hb/modules/header/modules/language-picker
    # blog modules
    - path: github.com/razonyang/hb/modules/blog
    - path: github.com/razonyang/hb/modules/blog/modules/breadcrumb
    - path: github.com/razonyang/hb/modules/blog/modules/giscus
    # - path: github.com/razonyang/hb/modules/blog/modules/disqus
    # - path: github.com/razonyang/hb/modules/blog/modules/utterances
    - path: github.com/razonyang/hb/modules/blog/modules/breadcrumb
    - path: github.com/razonyang/hb/modules/blog/modules/post-nav
    - path: github.com/razonyang/hb/modules/blog/modules/related-posts
    # docs modules
    - path: github.com/razonyang/hb/modules/docs
    - path: github.com/razonyang/hb/modules/docs/modules/breadcrumb
    - path: github.com/razonyang/hb/modules/docs/modules/doc-nav
    - path: github.com/razonyang/hb/modules/docs/modules/giscus
    # - path: github.com/razonyang/hb/modules/docs/modules/utterances
    # - path: github.com/razonyang/hb/modules/docs/modules/disqus

outputs:
  home:
    - HTML
    - Offline
    - RSS
    - SearchIndex
    # - StaticCMS
    # - StaticCMSConfig
    - WebAppManifest

taxonomies:
  tags: tags
  categories: categories
  series: series

build:
  writeStats: true

related:
  threshold: 20

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false
