baseURL: http://localhost/
title: Hugo Bootstrap Framework (HB)
copyright: "Copyright © 2022-{year} [Hugo Bootstrap Framework](https://hb.razonyang.com). All Rights Reserved."
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
disqusShortname: hb-site
enableRobotsTXT: true

module:
  # proxy: https://goproxy.cn
  imports:
    # recommended modules.
    - path: github.com/razonyang/hb/modules/meta/recommended

    # icons modules.
    - path: github.com/razonyang/hugo-mod-icons/vendors/font-awesome
  
    # blog comments engine.
    - path: github.com/razonyang/hb/modules/blog/modules/giscus
    # - path: github.com/razonyang/hb/modules/blog/modules/disqus
    # - path: github.com/razonyang/hb/modules/blog/modules/utterances
  
    # docs comments engine.
    - path: github.com/razonyang/hb/modules/docs/modules/giscus
    # - path: github.com/razonyang/hb/modules/docs/modules/utterances
    # - path: github.com/razonyang/hb/modules/docs/modules/disqus

    # others.
    # - path: github.com/razonyang/hb/modules/background-image

outputs:
  home:
    - HTML
    - Offline
    - RSS
    - SearchIndex
    - WebAppManifest

taxonomies:
  authors: authors
  tags: tags
  categories: categories
  series: series

build:
  writeStats: true

related:
  threshold: 20

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false
  tableOfContents:
    endLevel: 6
    startLevel: 2

