en:
  languageName: English
  weight: 1
      
zh-hans:
  languageName: 简体中文
  weight: 2

zh-hant:
  languageName: 繁體中文
  weight: 3

ar:
  languageName: "العربية"
  LanguageDirection: rtl
  weight: 4
